spring:
  application:
    name: zkwalletWithCustody

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zkwallet?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul
    username: root
    password: zkwallet

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100

encryption:
  aes:
    key: my-secret-password

jwt:
  secret: W32i/qpvlu5IGB3zWr4jZQUgQmbpm2thHOqHAOwofCZxn4fOfnFwF3Znd1qTYn72A2eR6aqvIAzrcWkx5wAbMA==

ethereum:
  rpc:
    url: http://127.0.0.1:8545
contract:
  mixer:
    address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"